### PR TITLE
Move docs from /Resources/doc/index.rst to /README.md

### PR DESCRIPTION
**Pull request by Doqnach**
Moved over the docs from /Resources/doc/index.rst over to the /README.md.

Added a packagist badge just because ;-].

### CODE REVIEW

**Comment by Doqnach** [comment]
Sorry about the additional commits from the `upstream/master` merge. New to the PR scene.

**Review by qpautrat — APPROVED** [review]
LGTM.

**Comment by qpautrat** [comment]
You need to rebase master in your own branch please.
Or you can create a new branch and cherry pick `820febf956cbdc33cd8088f2eb81fd3ea579a07d`

**Comment by Doqnach** [comment]
> You need to rebase master in your own branch please.
> Or you can create a new branch and cherry pick `820febf956cbdc33cd8088f2eb81fd3ea579a07d`

Started clean just to make sure. Should be better now. Will rebase nicely next time.

**Pull request merged**
